---

- name: Install Ansible
  hosts: vms
  user: root

  tasks:

  - name: Install packages
    action: yum pkg={{ item }} state=installed
    with_items:
    - git
    - ansible

  - name: Clone the workshop repository
    action: git repo=https://github.com/ansible-provisioning/ansible-workshop-v2.git
                dest=/root/workshop

  - name: Copy SSH key to root
    action: copy src=ssh-keys/id_rsa.workshop dest=/root/.ssh/id_rsa mode=0600
