---

- name: Configure Apache
  hosts: web-servers
  user: root

  vars_files:
  - config.yml

  handlers:

  - name: restart-apache
    service: name=httpd state=restarted

  tasks:

  - name: Install Apache and PHP
    yum: pkg={{ item }} state=installed
    with_items:
    - httpd
    - php-mysql

  - name: Add webapp vhost
    template: src=templates/etc/httpd/conf.d/webapp.conf dest=/etc/httpd/conf.d/
    notify:
    - restart-apache

  - name: Start Apache
    service: name=httpd state=started enabled=yes
