---

- name: Set up automatic application deployment repository
  hosts: vm-master
  user: root

  tasks:

  - name: Clone the workshop repository
    git: repo=/root/workshop
         dest=/root/deploy
         bare=yes
    ignore_errors: yes

  - name: Add post-receive hook to deploy
    copy: src=templates/post-receive
          dest=/root/deploy/hooks/
          mode=0755
