---
- name: Customize our image
  hosts: vms
  user: root

  tasks:
  - name: Configure DHCP
    action: copy src=templates/etc/sysconfig/network-scripts/ifcfg-eth0
                 dest=/etc/sysconfig/network-scripts/ifcfg-eth0
                 mode=0644

  - name: Set up console 11
    action: copy src=templates/etc/rc.d/rc.local
                 dest=/etc/rc.d/rc.local
                 mode=0755