---
- name: Ugly workaround for delegate_to bug in Ansible v1.8.4
  hosts: hypervisor
  remote_user: root

  tasks:
  - action: ping

- name: Create virtual images for Workshop
  hosts: vm-noname
  remote_user: root
  gather_facts: no

  vars:
    iso_image: boot.iso
    iso_dir: /tmp/workshop/iso
    kvm_dir: /tmp/workshop
    image_dir: /var/lib/libvirt/images
    centos_mirror: http://centos.cu.be/

  tasks:
  - name: Revoke old keys
    local_action: command ssh-keygen -R {{ ansible_ssh_host }}

  - name: Create temporary directory
    local_action: file dest={{ iso_dir }} state=directory

  - name: Template kickstart file
    local_action: template src=templates/centos-6.ks dest={{ iso_dir }}/ks.cfg

  - name: Template syslinux bootloader config
    local_action: template src=templates/isolinux.cfg dest={{ iso_dir }}/isolinux.cfg

  - name: Download boot images
    local_action: get_url url={{ centos_mirror }}/6/os/i386/{{ item }} dest={{ iso_dir }}
    with_items:
    - images/pxeboot/vmlinuz
    - images/pxeboot/initrd.img
    - isolinux/isolinux.bin

  - name: Create ISO boot image
    local_action: command mkisofs -r -N -allow-leading-dots -d -J -T -b isolinux.bin -c boot.cat -no-emul-boot -V "Ansible workshop" -boot-load-size 4 -boot-info-table -o {{ iso_image }} {{ iso_dir }}

  - name: Copy boot.iso to hypervisor
    action: copy src={{ iso_image }} dest={{ image_dir }}/vm-noname.iso
    delegate_to: hypervisor

  - name: Template VM configuration
    action: template src=templates/vm.xml dest={{ kvm_dir }}/{{ inventory_hostname }}.xml
    delegate_to: hypervisor

  - name: Allocate storage
    action: qemu_img dest={{ image_dir }}/{{ inventory_hostname }}.qcow2 size=3072 format=qcow2
    delegate_to: hypervisor

  - name: Create the VM
    action: virt_guest guest={{ inventory_hostname }} src={{ kvm_dir }}/{{ inventory_hostname }}.xml
    delegate_to: hypervisor

  - action: virt_boot guest={{ inventory_hostname }} boot=cdrom image={{ image_dir }}/vm-noname.iso
    delegate_to: hypervisor

  - name: Wait for the VM to start
    action: wait_for host={{ ansible_ssh_host }} port=22 state=started
    delegate_to: hypervisor

  - name: Wait for the kickstart to finish
    action: wait_for host={{ ansible_ssh_host }} port=22 state=stopped timeout=7200
    delegate_to: hypervisor

  - name: Wait for the VM to stop
    local_action: pause seconds=15

  - name: Boot the VM from the hard disk
    action: virt_boot guest={{ inventory_hostname }} boot=hd
    delegate_to: hypervisor

  - name: Wait for the VM to boot
    action: wait_for host={{ ansible_ssh_host }} port=22 state=started
    delegate_to: hypervisor

  - name: Configure CentOS mirror
    action: template src=templates/etc/yum.repos.d/CentOS-Base.repo dest=/etc/yum.repos.d/

  - name: Download EPEL
    action: get_url url=http://epel.mirror.nucleus.be/6/i386/epel-release-6-8.noarch.rpm dest=/tmp/

  - name: Install EPEL
    action: shell rpm -ivh /tmp/epel-release-6-8.noarch.rpm
    ignore_errors: yes

  - name: Install packages
    action: yum pkg={{ item }} enablerepo=epel-testing state=installed
    with_items:
    - ansible
    - git

#  - name: Update system
#    action: yum pkg=* state=latest

  - name: Clone the workshop repository
    action: git repo=https://github.com/ansible-provisioning/workshop-deployment-participant.git
                dest=/root/workshop

  - name: Clone the complete workshop repository
    action: git repo=https://github.com/ansible-provisioning/ansible-workshop-v2.git
                dest=/root/complete

  - name: Copy SSH key to root
    action: copy src=ssh-keys/id_rsa.workshop dest=/root/.ssh/id_rsa mode=0600

  - name: Configure DHCP
    action: copy src=templates/etc/sysconfig/network-scripts/ifcfg-eth0
                 dest=/etc/sysconfig/network-scripts/ifcfg-eth0
                 mode=0644

  - name: Remove persistent udev rules
    action: copy src=templates/etc/udev/rules.d/70-persistent-net.rules
                 dest=/etc/udev/rules.d/70-persistent-net.rules
                 mode=0644

  - name: Disable persistent udev rules generator
    action: file src=/dev/null
                 dest=/etc/udev/rules.d/75-persistent-net-generator.rules 
                 state=link
                 mode=0644

  - name: Copy Workshop configurator
    action: copy src=workshop-config
                 dest=/sbin/workshop-config
                 mode=0755

  - name: Configure Workshop configurator
    action: copy src=templates/etc/init/workshop.conf
                 dest=/etc/init/workshop.conf
                 mode=0644

  - action: command poweroff

  - local_action: pause seconds=15

  - action: fetch src={{ image_dir }}/{{ inventory_hostname }}.qcow2
                  dest=./
                  flat=yes
    delegate_to: hypervisor

  - local_action: command qemu-img convert -f qcow2 -O vmdk {{ inventory_hostname}}.qcow2 {{ inventory_hostname}}.vmdk
