---

- name: Configure MySQL
  hosts: database-servers
  user: root

  tasks:

  - name: Install MySQL
    yum: pkg={{ item }} state=installed
    with_items:
    - mysql-server
    - MySQL-python

  - name: Start MySQL
    service: name=mysqld state=started enabled=yes
