---

- name: Configure yum
  hosts: vms
  user: root

  vars_files:
  - config.yml

  tasks:

  - name: Configure CentOS mirror
    action: template src=templates/etc/yum.repos.d/CentOS-Base.repo dest=/etc/yum.repos.d/

  - name: Download EPEL
    action: get_url url=http://epel.mirror.nucleus.be/6/i386/epel-release-6-8.noarch.rpm dest=/tmp/

  - name: Install EPEL
    action: shell rpm -ivh /tmp/epel-release-6-8.noarch.rpm
    ignore_errors: yes
